[package]
name = "examples"
version = "0.0.0"
edition = "2018"

[[example]]
name = "context"
path = "context.rs"

[[example]]
name = "matplotlib"
path = "matplotlib.rs"

[[example]]
name = "rust-fn"
path = "rust-fn.rs"

[dependencies]
inline-python = { path = ".." }
pyo3 = "0.16.0"
